### ISSUE TITLE
[Feature request] Allow the razor sword upgrade to remain throughout song of time resets.

### ISSUE THREAD

**Issue by SamuelTheSuperb** [leoetlino/project-restoration#102] opened 2020-01-02 22:57 UTC
In my opinion, doing so would make the razor sword much more useful as a weapon, rather then just a pathway to the gilded sword.

**Comment by GeneraLight** [comment] 2020-01-04 03:15
This issue was discussed before and got rejected. But I agree. This really needs to be changed. The Razor Sword's presence and usefulness is basically non-existent. This would flesh out the variety of the game.

**Comment by Luigimeansme** [comment] 2020-01-04 03:25
It would be completely pointless. The Razor Sword already only lasts 100 swings, whether they hit anything or not, and costs 100 rupees. However, for no monetary cost (only Gold Dust gotten from a minigame that is ALSO free) you get a sword that lasts forever. Most people would just skip to the Gilded Sword anyway

**Comment by leoetlino** [comment] 2020-01-04 18:56
Duplicate of #82

**Closed by leoetlino** 2020-01-04 18:56 UTC
Labels: enhancement
