### ISSUE TITLE
An option to scale HUD or just different options to download for the HD Top screen HUD Version

### ISSUE THREAD

**Issue by GoldenMajora** [leoetlino/project-restoration#234] opened 2022-11-03 07:05 UTC
This would be a great option for people who are emulating  MM3D on a lower end device that needs to stay at 1x, such as a phone. At 1x the HUD is blurry and hard to see. So an option somehow to scale the HUD up and down to be able to see it on lower resolutions would be lovely.

**Comment by leoetlino** [comment] 2022-11-04 00:10
Duplicate of #208

**Closed as not planned by leoetlino** 2022-11-04 00:10 UTC
Labels: enhancement
