### ISSUE TITLE
Hud mod looks bad at 2x scale

### ISSUE THREAD

**Issue by jvook** [leoetlino/project-restoration#208] opened 2021-10-29 15:52 UTC
![Untitled](https://user-images.githubusercontent.com/17225171/139465256-d52b7df9-cac9-4a5a-9eda-f37de7a529cc.jpg)

I don't think it would take much to modify the layout so that it scales well on 2x resolution.  It's really only the button labels and the d-pad icon, otherwise it looks good.

**Comment by leoetlino** [comment] 2021-10-29 18:39
> I don't think it would take much to make the texture an even multiple that scales down to 2x

Well, the problem isn't the texture (not that you can arbitrarily resize the texture anyway -- you're limited by the original texture shape and layout).

The issue is that the HUD uses fractional scaling to simulate a higher resolution viewport, and in your case there literally aren't enough pixels to avoid aliasing issues. It might be possible to move the D-Pad one pixel to the left/right to try to get it to look better but I don't think this is worth the effort when (a) it's still going to look imperfect (and will never look as well as at higher resolutions); (b) this will almost certainly break if the layout is updated for whatever reason in the future, and require extra effort to fix; (c) this will not fix ugliness elsewhere, e.g. for the item buttons, and as I said earlier the HD HUD mod is only supported at HD resolutions.

Are you using integrated graphics? 3x should be quite doable even on an entry-level GPU... I think you'll get a much better experience after upgrading your hardware if performance is the only thing keeping you from running the game at 720p+. Even ignoring the UI issues in your screenshots there's still some very obvious aliasing and blurriness. It'd be a shame to run the game at 480p when you seemingly have a 4k display...

**Comment by leoetlino** [comment] 2022-01-01 23:56
Closing because there's not much I can do about this.

**Closed by leoetlino** 2022-01-01 23:56 UTC
