### ISSUE TITLE
Crashes after intro

### ISSUE THREAD

**Issue by Siju21** [leoetlino/project-restoration#166] opened 2021-01-07 04:15 UTC
It's crashing for me after the intro cutscene, after Link loses hold of Epona. I am using the original gamecart on a New 3ds XL. It's crashing for me with the regardless of whether the eshop update is installed. I have tried all 3 file sets with both revision 1.0 and 1.1

**Comment by leoetlino** [comment] 2021-01-07 08:33
Can you screenshot the contents of the /luma/titles/TITLE_ID/ folder on your SD card?

**Comment by Siju21** [comment] 2021-01-20 20:47
<img width="1032" alt="Screen Shot 2021-01-20 at 3 46 29 PM" src="https://user-images.githubusercontent.com/42592643/105232722-c7009d80-5b36-11eb-9c42-a89ce681c99b.png">

**Comment by leoetlino** [comment] 2021-01-20 20:49
Can you show what's in the RomFS folder as well?

Also, make sure you are NOT using the HD HUD mod if you are playing on a 3DS.

**Comment by Siju21** [comment] 2021-01-20 20:50
<img width="1032" alt="Screen Shot 2021-01-20 at 3 50 20 PM" src="https://user-images.githubusercontent.com/42592643/105232978-35456000-5b37-11eb-8680-2d738329e93c.png">
Not using the HD HUD mod. Just the normal mod.

**Comment by Siju21** [comment] 2021-01-20 20:52
I saw some posts regarding other mods with the same arm11 exception. They said they solved it by dumping their title seed in FBI, but when I do it, I get an error 404 not found.

**Comment by leoetlino** [comment] 2021-01-20 21:00
Hmm, unfortunately I have no idea what's wrong... This is the first time I've heard of a crash after the intro cutscene on a 3DS.

I know it's possible to get a crash after the intro if you accidentally mix the HD HUD version with the regular version and forget the custom HD layout files. On a 3DS, it shouldn't be possible though, especially when Luma3DS ensures that you are not using the wrong patch...

Could you remove the music mod just in case a recent Project Restoration update has made it incompatible? Just rename the RomFS folder to something else to disable it

**Comment by Siju21** [comment] 2021-01-20 21:01
I tried that too... It just crashes immediately after Link falls off Epona.

**Comment by Siju21** [comment] 2021-01-20 21:02
Just to be sure, on a New 3ds XL, I have to rename legacy exheader to exheader? If so, then I'm afraid my 3ds doesn't like your mod.

**Comment by leoetlino** [comment] 2021-01-20 21:08
Yes, you need to rename the legacy exheader to exheader.bin to use the mod on a 3DS.

Does the game actually work fine if you don't use the patch? It sounds like the game might be corrupted... I can't reproduce the crash and I think I'd have received more bug reports for such a severe issue...

**Comment by Siju21** [comment] 2021-01-20 21:10
The game works fine without your mod. It works fine with and without the music mod. Only your mod is making my game crash. I loaded another save that is past the intro, and it seems to be working okay. It's just a bummer that I can't start over.

**Comment by leoetlino** [comment] 2021-01-20 21:12
Hmm, I see. Any chance you could post the crash screen or the crash dump file? It's certainly possible there is a bug in the patch.

**Comment by Siju21** [comment] 2021-01-20 21:16
Rename the extension to .dmp
[crash_dump_00000003.txt](https://github.com/leoetlino/project-restoration/files/5845327/crash_dump_00000003.txt)

**Comment by leoetlino** [comment] 2021-01-20 21:19
Are you sure that's the correct dump? This is what I see:

```
Processor: ARM11 (core 1)
Exception type: prefetch abort (svcBreak: panic)
Current process: loader (0000000000000000)
```

The crash report indicates it's crashing in the loader sysmodule, before the game is even launched.

**Comment by Siju21** [comment] 2021-01-20 21:20
that's the only dump in my folder

**Comment by leoetlino** [comment] 2021-01-20 21:22
Weird... Could you please take a photo of your 3DS screens after the intro crash then?

**Comment by Siju21** [comment] 2021-01-20 21:24
I can try later today. Don't have my phone on me atm. Just a hunch, does it matter that I have clock+L2 enabled in Luma? I also just read that it causes issues with certain mods.

**Comment by leoetlino** [comment] 2021-01-20 21:29
Possibly, it's not unusual for games to outright crash if you run them with radically different clock speeds or cache behavior... I don't think Project Restoration makes any assumption about console timing, but it's probably worth testing again after disabling that option

**Comment by Siju21** [comment] 2021-01-20 21:29
I seem to have fixed it... I uninstalled update 1.1 through FBI and then used v100 files.

**Comment by Siju21** [comment] 2021-01-20 21:31
Yup, fixed.

**Comment by leoetlino** [comment] 2021-01-20 21:32
:thinking: very weird, but I'm glad to hear it's now working for you! I'll keep this issue open in case somebody else has the same problem or until I figure out what the problem is (considering that 1.1 is supposed to work fine)...

**Comment by Syko7956** [comment] 2021-04-17 00:34
Might wanna close this issue

**Comment by leoetlino** [comment] 2021-04-18 09:26
Yeah, it doesn't seem like this is a particularly common issue.

**Closed by leoetlino** 2021-04-18 09:26 UTC
